[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"] # Paksa instal Node.js versi 18 dan NPM

[phases.install]
cmds = ["npm install --prefix bot"] # Instal library yang ada di folder bot

[start]
cmd = "node bot/index.js" # Jalankan file bot kamu